python -m gspan_mining -s 39 ./gspan_data/gspan01.data > ./gspan_preoutput/gspan_output01.data
python -m gspan_mining -s 90 ./gspan_data/gspan02.data > ./gspan_preoutput/gspan_output02.data
python -m gspan_mining -s 6 ./gspan_data/gspan03.data > ./gspan_preoutput/gspan_output03.data
python -m gspan_mining -s 14 ./gspan_data/gspan04.data > ./gspan_preoutput/gspan_output04.data
python -m gspan_mining -s 18 ./gspan_data/gspan05.data > ./gspan_preoutput/gspan_output05.data
python -m gspan_mining -s 6 ./gspan_data/gspan06.data > ./gspan_preoutput/gspan_output06.data
python -m gspan_mining -s 12 ./gspan_data/gspan07.data > ./gspan_preoutput/gspan_output07.data
python -m gspan_mining -s 6 ./gspan_data/gspan08.data > ./gspan_preoutput/gspan_output08.data
python -m gspan_mining -s 8 ./gspan_data/gspan09.data > ./gspan_preoutput/gspan_output09.data
python -m gspan_mining -s 3 ./gspan_data/gspan10.data > ./gspan_preoutput/gspan_output10.data
python -m gspan_mining -s 12 ./gspan_data/gspan11.data > ./gspan_preoutput/gspan_output11.data
python -m gspan_mining -s 12 ./gspan_data/gspan12.data > ./gspan_preoutput/gspan_output12.data
python -m gspan_mining -s 6 ./gspan_data/gspan13.data > ./gspan_preoutput/gspan_output13.data
python -m gspan_mining -s 3 ./gspan_data/gspan14.data > ./gspan_preoutput/gspan_output14.data
python -m gspan_mining -s 2 ./gspan_data/gspan15.data > ./gspan_preoutput/gspan_output15.data
python -m gspan_mining -s 6 ./gspan_data/gspan16.data > ./gspan_preoutput/gspan_output16.data
python -m gspan_mining -s 16 ./gspan_data/gspan17.data > ./gspan_preoutput/gspan_output17.data
python -m gspan_mining -s 6 ./gspan_data/gspan18.data > ./gspan_preoutput/gspan_output18.data
python -m gspan_mining -s 8 ./gspan_data/gspan19.data > ./gspan_preoutput/gspan_output19.data
python -m gspan_mining -s 2 ./gspan_data/gspan20.data > ./gspan_preoutput/gspan_output20.data
python -m gspan_mining -s 6 ./gspan_data/gspan21.data > ./gspan_preoutput/gspan_output21.data
python -m gspan_mining -s 7 ./gspan_data/gspan22.data > ./gspan_preoutput/gspan_output22.data
